---
tags: [cpp, exception]
---

# Exception Safety

For function with the modifier `noexcept`, if it encounters any kind of
exception, it will simply call `terminate()` which immediately terminate the
current running program.

Avoid throwing exception in destructor as it violates the
[RAII](202202012306.md) philosophy. Instead, we should provide a regular
function to perform resource management in order to react to the exception
accordingly. We can choose to either terminate or swallow the exceptions coming
from its scape as the default behaviour.
