---
tags: [cpp, exception]
---

# Exception Safety

For function with the modifier `noexcept`, if it encounters any kind of
exception, it will simply call `terminate()` which immediately terminate the
current running program.
